export default {
  SET_COMMENTS: 'SET_COMMENTS',
  ADD_COMMENT: 'ADD_COMMENT',
  FETCH_COMMENTS: 'FETCH_COMMENTS',

  // models
  FETCH_MODELS: 'FETCH_MODELS',
  SET_MODELS: 'SET_MODELS',

  // revisions
  FETCH_REVISIONS: 'FETCH_REVISIONS',
  SET_REVISIONS: 'SET_REVISIONS',
}

